apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  namespace: default
spec:
  replicas: 4
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx2
        image: nginx

